const viText = {
  "Chăm sóc khách hàng": "Chăm sóc khách hàng",
  "Kiểm tra đơn hàng": "Kiểm tra đơn hàng",
  "Đăng nhập": "Đăng nhập",
  "Đăng ký": "Đăng ký",
  "Tìm kiếm": "Tìm kiếm",
  "Giỏ hàng": "Giỏ hàng",
  "Dành riêng cho bạn": "Dành riêng cho bạn",
  "Thêm vào giỏ": "Thêm vào giỏ",
  "Đã bán": "Đã bán",
  "Quần áo": "Quần áo",
  "Mỹ phẩm": "Mỹ phẩm",
  "Đồ gia dụng": "Đồ gia dụng",
  "Thiết bị điện tử": "Thiết bị điện tử",
  "Thể thao": "Thể thao",
  "Sức khỏe": "Sức khỏe",
  "Đồng hồ": "Đồng hồ",
  "Túi xách": "Túi xách",
  "Mã giảm giá": "Mã giảm giá",
  "Nạp thẻ": "Nạp thẻ & eVoucher",
  "Xem thêm sản phẩm": "Xem thêm sản phẩm",
  "Hệ thống gian hàng chính hãng": "Hệ thống gian hàng chính hãng",
  "Toàn quốc, theo dõi đơn dễ dàng": "Toàn quốc, theo dõi đơn dễ dàng",
  "Giao hàng nhanh": "Giao hàng nhanh chóng",
  "Đổi trả linh hoạt": "Đổi trả linh hoạt",
  "Miễn phí trong 15 ngày": "Miễn phí trong 15 ngày",
  "Thanh toán an toàn": "Thanh toán an toàn",
  "Nhiều hình thức, bảo mật": "Nhiều hình thức, bảo mật",
  "Trợ giúp": "Trợ giúp",
  "Trung tâm hỗ trợ": "Trung tâm hỗ trợ",
  "Uy tín - đa dạng - giá tốt": "Uy tín - đa dạng - giá tốt",
  "Hướng dẫn mua hàng": "Hướng dẫn mua hàng",
  "Theo dõi đơn hàng": "Theo dõi đơn hàng",
  "Chính sách đổi trả": "Chính sách đổi trả",
  "Về Lazada": "Về Lazada",
  "Giới thiệu": "Giới thiệu",
  "Tuyển dụng": "Tuyển dụng",
  "Điều khoản sử dụng": "Điều khoản sử dụng",
  "Bảo mật thông tin": "Bảo mật thông tin",
  "Liên hệ": "Liên hệ",
  "Đăng ký nhận tin": "Đăng ký nhận tin",
  "Nhập email của bạn": "Nhập email của bạn",
  "© 2025 Lazada — Một dự án demo giao diện.": "© 2025 Lazada — Một dự án demo giao diện.",
  "CHỌN TẤT CẢ": "CHỌN TẤT CẢ (",
  "SẢN PHẨM)": "SẢN PHẨM )",
  "Địa Chỉ Nhận Hàng": "Địa Chỉ Nhận Hàng",
  "Thay Đổi": "Thay Đổi",
  "Chưa có sản phẩm nào trong giỏ hàng.": "Chưa có sản phẩm nào trong giỏ hàng.",
  "Thông tin đơn hàng": "Thông tin đơn hàng",
  "Phí vận chuyển": "Phí vận chuyển",
  "Tổng cộng": "Tổng cộng",
  "ÁP DỤNG": "ÁP DỤNG",
  "THANH TOÁN": "THANH TOÁN(",
  "Đã bao gồm": "Đã bao gồm VAT (nếu có)",
  "Tạm tính": "Tạm tính",
  "sản phẩm": "sản phẩm",
  "Chi tiết đơn hàng": "Chi tiết đơn hàng",
  "Mã đơn": "Mã đơn:",
  "Đang giao": "Đang giao",
  "Đặt ngày": "Đặt ngày:",
  "Số lượng": "Số lượng:",
  "Phương thức thanh toán": "Phương thức thanh toán:",
  "Nhận hàng": "Nhận hàng:",
  "Trạng thái thanh toán": "Trạng thái thanh toán:",
  "Địa chỉ:": "Địa chỉ:",
  "Đơn vị vận chuyển": "Đơn vị vận chuyển:",
  "Phí ship:": "Phí ship:",
  "Tổng tiền:": "Tổng tiền:",
  "Voucher đã dùng:": "Voucher đã dùng:",
  "Đã giao:": "Đã giao:",
  "Chưa thanh toán": "Chưa thanh toán",
  "Hoàn tất": "Hoàn tất",
  "Đã thanh toán": "Đã thanh toán",
  "Hủy đơn": "Hủy đơn",
  "Theo dõi đơn hàng": "Theo dõi đơn hàng",
  "Đánh giá sản phẩm": "Đánh giá sản phẩm",
  "Mua lại": "Mua lại",
  "Liên hệ CSKH": "Liên hệ CSKH",
  "Mã vận đơn:": "Mã vận đơn:",
  "Chi tiết đơn hàng": "Chi tiết đơn hàng",
  "Chờ đóng gói": "Chờ đóng gói",
  "Chờ lấy hàng": "Chờ lấy hàng",
  "Chờ giao hàng": "Chờ giao hàng",
  "Đang vận chuyển": "Đang vận chuyển",
  "Giao hàng thành công": "Giao hàng thành công",
  "Thông tin kiện hàng": "Thông tin kiện hàng",
  "Người nhận hàng:": "Người nhận hàng:",
  "Hình thức giao hàng": "Hình thức giao hàng",
  "Ngày khách hàng tạo đơn hàng:": "Ngày khách hàng tạo đơn hàng:",
  "Ngày nhận hàng dự kiến:": "Ngày nhận hàng dự kiến:",
  "Lịch sử vận chuyển": "Lịch sử vận chuyển",
  "Đơn hàng đã được nhận tại trạm giao nhận": "Đơn hàng đã được nhận tại trạm giao nhận",
  "Đơn hàng rời khỏi trung tâm phân loại": "Đơn hàng rời khỏi trung tâm phân loại",
  "Đơn hàng đã được nhận tại trung tâm phân loại": "Đơn hàng đã được nhận tại trung tâm phân loại",
  "Đơn vị vận chuyển đã lấy hàng": "Đơn vị vận chuyển đã lấy hàng",
  "Người gửi đang chuẩn bị hàng": "Người gửi đang chuẩn bị hàng",
  "Đơn hàng đã được đặt": "Đơn hàng đã được đặt",
  "Bách hóa": "Bách hóa",
  "Bánh ăn sáng": "Bánh ăn sáng",
  "Đồ nướng & tráng miệng": "Đồ nướng & tráng miệng",
  "Bánh trung thu": "Bánh trung thu",
  "Thương hiệu:": "Thương hiệu:",
  "Mua sắm kết hợp siêu ưu đãi Thanh toán": "Mua sắm kết hợp siêu ưu đãi Thanh toán",
  "THAY ĐỔI": "THAY ĐỔI",
  "Giao đến:": "Giao đến:",
  "Đảm bảo nhận hàng vào 25 thg 9": "Đảm bảo nhận hàng vào 25 thg 9",
  "Miễn phí vận chuyển khi mua từ 50.000đ": "Miễn phí vận chuyển khi mua từ 50.000đ",
  "100% chính hãng • Đổi trả 30 ngày miễn phí": "100% chính hãng • Đổi trả 30 ngày miễn phí",
  "Số lượng:": "Số lượng:",
  "Mua ngay": "Mua ngay",
  "Gian hàng": "Gian hàng",
  "Gian hàng chính hãng": "Gian hàng chính hãng",
  "Top1 Shop thuộc mục Bánh ăn sáng": "Top1 Shop thuộc mục Bánh ăn sáng",
  "3 năm hoạt động": "3 năm hoạt động",
  "Shop yêu thích": "Shop yêu thích",
  "Đánh giá tích cực": "Đánh giá tích cực",
  "Đánh giá": "Đánh giá",
  "Chi tiết": "Chi tiết",
  "Gợi ý cho bạn": "Gợi ý cho bạn",
  "(233 đánh giá)": "(233 đánh giá)",
  "Tất cả": "Tất cả",
  "Có hình / video": "Có hình / video",
  "Khách đã mua lại": "Khách đã mua lại",
  "Sắp xếp: Liên quan": "Sắp xếp: Liên quan",
  "Mới nhất": "Mới nhất",
  "7 ngày trước": "7 ngày trước",
  "Hữu ích (1)": "Hữu ích (1)",
  "Hữu ích (0)": "Hữu ích (0)",
  "1 tuần trước": "1 tuần trước",
  "Chi tiết sản phẩm": "Chi tiết sản phẩm",
  "Otherdetail1": "Đây là sản phẩm được bán bởi Người bán bên thứ ba và việc xuất hóa đơn VAT (nếu áp dụng) sẽ được thực hiện bởi Nhà Bán Hàng theo quy định của pháp luật",
  "THU GỌN": "THU GỌN",
  "Thương hiệu": "Thương hiệu",
  "Mooncake Type": "Loại bánh trung thu",
  "Cách đóng gói": "Cách đóng gói",
  "Giao hàng": "Giao hàng",
  "Xuất xứ": "Xuất xứ",
  "Loại sản phẩm": "Loại sản phẩm",
  "Hạn sử dụng": "Hạn sử dụng",
  "Loại bánh": "Loại bánh",
  "SKU": "SKU",
  "Cùng cửa hàng bán": "Cùng cửa hàng bán",
  "Có thể bạn cũng thích": "Có thể bạn cũng thích",
  "Tìm kiếm trên Lazada, sản phẩm, thương hiệu...": "Tìm kiếm trên Lazada, sản phẩm, thương hiệu...",
  "Nhập email của bạn": "Nhập email của bạn",
  "Gửi mã OTP qua Zalo": "Gửi mã OTP qua Zalo",
  "Kết quả": "Kết quả",
  "Lịch sử tìm kiếm": "Lịch sử tìm kiếm",
  "Từ khóa phổ biến": "Từ khóa phổ biến",
  "áo thể thao": "áo thể thao",
  "giày chạy bộ": "giày chạy bộ",
  "đồng hồ thông minh": "đồng hồ thông minh",
  "tai nghe bluetooth": "tai nghe bluetooth",
  "kem chống nắng": "kem chống nắng",
  "điện thoại": "điện thoại",
  "Danh mục gợi ý": "Danh mục gợi ý",
  "Sản phẩm phổ biến": "Sản phẩm phổ biến",
  "Tìm kiếm sản phẩm, thương hiệu...": "Tìm kiếm sản phẩm, thương hiệu...",
  "Bộ lọc": "Bộ lọc",
  "Hãng": "Hãng",
  "Từ 10%": "Từ 10%",
  "Giảm giá": "Giảm giá",
  "Nơi bán": "Nơi bán",
  "Sắp xếp": "Sắp xếp",
  "Phổ biến": "Phổ biến",
  "Giá tăng dần": "Giá tăng dần",
  "Giá giảm dần": "Giá giảm dần",
  "Giảm giá nhiều": "Giảm giá nhiều",
  "Từ 20%": "Từ 20%",
  "Từ 30%": "Từ 30%",
  "Từ 40%": "Từ 40%",
  "Tìm kiếm trong vợt cầu lông...": "Tìm kiếm trong vợt cầu lông...",
  "Trang chủ": "Trang chủ",
  "Vợt cầu lông": "Vợt cầu lông",
  "Gợi ý": "Gợi ý",
  "Miễn phí vận chuyển đơn từ 50.000đ": "Miễn phí vận chuyển đơn từ 50.000đ",
  "Đảm bảo nhận hàng trong 2-3 ngày": "Đảm bảo nhận hàng trong 2-3 ngày",
  "Màu:": "Màu:",
  "Xanh than": "Xanh than",
  "Đen": "Đen",
  "2 ngày trước": "2 ngày trước",
  "Hữu ích (3)": "Hữu ích (3)",
  "Thông số kỹ thuật": "Thông số kỹ thuật",
  "Trọng lượng": "Trọng lượng",
  "Độ cứng": "Độ cứng",
  "Điểm cân bằng": "Điểm cân bằng",
  "Vật liệu khung": "Vật liệu khung",
  "Chu vi cán": "Chu vi cán",
};
const enText = {
  "Chăm sóc khách hàng": "Customer Care",
  "Kiểm tra đơn hàng": "Track Order",
  "Đăng nhập": "Login",
  "Đăng ký": "Register",
  "Tìm kiếm": "Search",
  "Giỏ hàng": "Cart",
  "Dành riêng cho bạn": "Recommended for you",
  "Thêm vào giỏ": "Add to cart",
  "Đã bán": "Sold",
  "Quần áo": "Clothing",
  "Mỹ phẩm": "Cosmetics",
  "Đồ gia dụng": "Home Appliances",
  "Thiết bị điện tử": "Electronics",
  "Thể thao": "Sports",
  "Sức khỏe": "Health",
  "Đồng hồ": "Watches",
  "Túi xách": "Bags",
  "Mã giảm giá": "Discount Codes",
  "Nạp thẻ": "Top-up & eVoucher",
  "Xem thêm sản phẩm": "See more products",
  "Hệ thống gian hàng chính hãng": "Official Store System",
  "Giao hàng nhanh": "Fast Delivery",
  "Uy tín - đa dạng - giá tốt": "Reliable - diverse - good prices",
  "Toàn quốc, theo dõi đơn dễ dàng": "Nationwide, easy order tracking",
  "Đổi trả linh hoạt": "Flexible Returns",
  "Miễn phí trong 15 ngày": "Free within 15 days",
  "Thanh toán an toàn": "Secure Payment",
  "Nhiều hình thức, bảo mật": "Multiple methods, secure",
  "Trợ giúp": "Help",
  "Trung tâm hỗ trợ": "Support Center",
  "Hướng dẫn mua hàng": "Shopping Guide",
  "Theo dõi đơn hàng": "Track Order",
  "Chính sách đổi trả": "Return Policy",
  "Về Lazada": "About Lazada",
  "Giới thiệu": "Introduction",
  "Tuyển dụng": "Careers",
  "Điều khoản sử dụng": "Terms of Use",
  "Bảo mật thông tin": "Privacy Policy",
  "Liên hệ": "Contact",
  "Đăng ký nhận tin": "Subscribe to Newsletter",
  "Nhập email của bạn": "Enter your email",
  "© 2025 Lazada — Một dự án demo giao diện.": "© 2025 Lazada — A demo interface project.",
  "CHỌN TẤT CẢ": "SELECT ALL (",
  "SẢN PHẨM)": "PRODUCTS )",
  "Địa Chỉ Nhận Hàng": "Shipping Address",
  "Thay Đổi": "Change",
  "Chưa có sản phẩm nào trong giỏ hàng.": "No products in the cart.",
  "Thông tin đơn hàng": "Order Summary",
  "Phí vận chuyển": "Shipping Fee",
  "Tổng cộng": "Total",
  "ÁP DỤNG": "APPLY",
  "THANH TOÁN": "CHECKOUT(",
  "Đã bao gồm": "Including VAT (if any)",
  "Tạm tính": "Subtotal",
  "sản phẩm": "products",
  "Chi tiết đơn hàng": "Order Details",
  "Mã đơn": "Order ID:",
  "Đang giao": "Shipping",
  "Đặt ngày": "Order Date:",
  "Số lượng": "Quantity:",
  "Phương thức thanh toán": "Payment Method:",
  "Nhận hàng": "Recipient:",
  "Trạng thái thanh toán": "Payment Status:",
  "Địa chỉ:": "Address:",
  "Đơn vị vận chuyển": "Shipping Carrier:",
  "Phí ship:": "Shipping Fee:",
  "Tổng tiền:": "Total:",
  "Voucher đã dùng:": "Used Voucher:",
  "Đã giao:": "Delivered:",
  "Chưa thanh toán": " Unpaid",
  "Hoàn tất": "Completed",
  "Đã thanh toán": " Paid",
  "Hủy đơn": "Cancel Order",
  "Theo dõi đơn hàng": "Track Order",
  "Đánh giá sản phẩm": "Rate Product",
  "Mua lại": "Buy Again",
  "Liên hệ CSKH": "Contact Customer Service",
  "Mã vận đơn:": "Tracking Number:",
  "Chi tiết đơn hàng": "Order Details",
  "Chờ đóng gói": "Pending Packaging",
  "Chờ lấy hàng": "Pending Pickup",
  "Chờ giao hàng": "Pending Delivery",
  "Đang vận chuyển": "In Transit",
  "Giao hàng thành công": "Delivered",
  "Thông tin kiện hàng": "Package Information",
  "Người nhận hàng:": "Recipient:",
  "Hình thức giao hàng": "Delivery Method",
  "Ngày khách hàng tạo đơn hàng:": "Order Created Date:",
  "Ngày nhận hàng dự kiến:": "Estimated Delivery Date:",
  "Lịch sử vận chuyển": "Shipping History",
  "Đơn hàng đã được nhận tại trạm giao nhận": "Order received at the delivery station",
  "Đơn hàng rời khỏi trung tâm phân loại": "Order departed from sorting center",
  "Đơn hàng đã được nhận tại trung tâm phân loại": "Order received at sorting center",
  "Đơn vị vận chuyển đã lấy hàng": "Carrier has picked up the order",
  "Người gửi đang chuẩn bị hàng": "Sender is preparing the order",
  "Đơn hàng đã được đặt": "Order has been placed",
  "Bách hóa": "Groceries",
  "Bánh ăn sáng": "Breakfast Pastries",
  "Đồ nướng & tráng miệng": "Baked Goods & Desserts",
  "Bánh trung thu": "Mooncakes",
  "Thương hiệu:": "Brand:",
  "Mua sắm kết hợp siêu ưu đãi Thanh toán": "Combo Shopping Super Deals Checkout",
  "THAY ĐỔI": "CHANGE",
  "Giao đến:": "Deliver to:",
  "Đảm bảo nhận hàng vào 25 thg 9": "Guaranteed delivery by Sep 25",
  "Miễn phí vận chuyển khi mua từ 50.000đ": "Free shipping on orders over 50,000đ",
  "100% chính hãng • Đổi trả 30 ngày miễn phí": "100% Authentic • 30-day Free Returns",
  "Số lượng:": "Quantity:",
  "Mua ngay": "Buy Now",
  "Gian hàng": "Store",
  "Gian hàng chính hãng": "Official Store",
  "Top1 Shop thuộc mục Bánh ăn sáng": "Top1 Shop in Breakfast Pastries",
  "3 năm hoạt động": "3 years active",
  "Shop yêu thích": "Favorite Shop",
  "Đánh giá tích cực": "Positive Reviews",
  "Đánh giá": "Reviews",
  "Chi tiết": "Details",
  "Gợi ý cho bạn": "Suggestions for you",
  "(233 đánh giá)": "(233 reviews)",
  "Tất cả": "All",
  "Có hình / video": "With images/videos",
  "Khách đã mua lại": "Repeat customers",
  "Sắp xếp: Liên quan": "Sort by: Relevance",
  "Mới nhất": "Newest",
  "7 ngày trước": "7 days ago",
  "Hữu ích (1)": "Helpful (1)",
  "Hữu ích (0)": "Helpful (0)",
  "1 tuần trước": "1 week ago",
  "Chi tiết sản phẩm": "Product Details",
  "Otherdetail1": "This product is sold by a third-party seller and VAT invoice (if applicable) will be issued by the Seller in accordance with legal regulations",
  "THU GỌN": "COLLAPSE",
  "Thương hiệu": "Brand",
  "Mooncake Type": "Mooncake Type",
  "Cách đóng gói": "Packaging",
  "Giao hàng": "Delivery",
  "Xuất xứ": "Origin",
  "Loại sản phẩm": "Product Type",
  "Hạn sử dụng": "Shelf Life",
  "Loại bánh": "Cake Type",
  "SKU": "SKU",
  "Cùng cửa hàng bán": "From the same store",
  "Có thể bạn cũng thích": "You may also like",
  "Tìm kiếm trên Lazada, sản phẩm, thương hiệu...": "Search Lazada, products, brands...",
  "Nhập email của bạn": "Enter your email",
  "Gửi mã OTP qua Zalo": "Send OTP via Zalo",
  "Kết quả": "Results",
  "Lịch sử tìm kiếm": "Search History",
  "Từ khóa phổ biến": "Popular Keywords",
  "áo thể thao": "sports shirt",
  "giày chạy bộ": "running shoes",
  "đồng hồ thông minh": "smart watch",
  "tai nghe bluetooth": "bluetooth headphones",
  "kem chống nắng": "sunscreen",
  "điện thoại": "phone",
  "Danh mục gợi ý": "Suggested Categories",
  "Sản phẩm phổ biến": "Popular Products",
  "Tìm kiếm sản phẩm, thương hiệu...": "Search products, brands...",
  "Bộ lọc": "Filter",
  "Hãng": "Brand",
  "Từ 10%": "From 10%",
  "Giảm giá": "Discount",
  "Nơi bán": "Location",
  "Sắp xếp": "Sort",
  "Phổ biến": "Popular",
  "Giá tăng dần": "Price: Low to High",
  "Giá giảm dần": "Price: High to Low",
  "Giảm giá nhiều": "Most Discounted",
  "Từ 20%": "From 20%",
  "Từ 30%": "From 30%",
  "Từ 40%": "From 40%",
  "Tìm kiếm trong vợt cầu lông...": "Search in badminton rackets...",
  "Trang chủ": "Home",
  "Vợt cầu lông": "Badminton Rackets",
  "Gợi ý": "Suggestions",
  "Miễn phí vận chuyển đơn từ 50.000đ": "Free shipping on orders over 50,000đ",
  "Đảm bảo nhận hàng trong 2-3 ngày": "Guaranteed delivery within 2-3 days",
  "Màu:": "Color:",
  "Xanh than": "Navy Blue",
  "Đen": "Black",
  "2 ngày trước": "2 days ago",
  "Hữu ích (3)": "Helpful (3)",
  "Thông số kỹ thuật": "Specifications",
  "Trọng lượng": "Weight",
  "Độ cứng": "Stiffness",
  "Điểm cân bằng": "Balance Point",
  "Vật liệu khung": "Frame Material",
  "Chu vi cán": "Handle Girth",
  "Bảo hành": "Warranty",
  "Thương hiệu": "Brand",
  "Xuất xứ": "Origin",
};

function switchLanguage(lang) {
  const dict = lang === 'en' ? enText : viText;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (dict[key]) el.textContent = dict[key];
  });
  // Đổi placeholder cho các input có data-i18n-placeholder
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    if (dict[key]) el.placeholder = dict[key];
  });
  document.getElementById('langToggleBtn').classList.toggle('active', lang === 'en');
  localStorage.setItem('lang', lang);
}

document.getElementById('langToggleBtn').onclick = function() {
  console.log("Lazada clone by YourName - 2024");
  const current = localStorage.getItem('lang') === 'en' ? 'vi' : 'en';
  switchLanguage(current);
};

window.addEventListener('DOMContentLoaded', function() {
  const lang = localStorage.getItem('lang') || 'vi';
  switchLanguage(lang);
});